# Generated by Django 5.0 on 2023-12-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_shop_url_shopcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='shops',
            field=models.ManyToManyField(related_name='shops', to='backend.shop'),
        ),
    ]
