# Generated by Django 5.0 on 2023-12-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_shops_category_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='shop',
        ),
    ]
