# Generated by Django 5.0 on 2023-12-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_category_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='shop',
            field=models.ManyToManyField(related_name='shops', to='backend.shop'),
        ),
    ]
